name: frontend
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  intl: ^0.17.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  provider: ^6.0.3
  cupertino_icons: ^1.0.6
  go_router: ^14.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
