name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  intl: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  avatar_stack: ^1.2.0
  web_socket_channel: ^3.0.0
  shared_preferences: ^2.2.3
  fluttertoast: ^8.0.9
  provider: ^6.0.3
  cupertino_icons: ^1.0.6
  go_router: ^14.1.3
  image_picker: ^1.1.2
  http_parser: ^4.0.0
  google_sign_in: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  easy_localization: ^3.0.0
  flutter_translate: ^3.0.0
  xml: ^6.5.0
  file_picker: ^8.0.5
  weather: ^3.1.1
  lottie: ^3.1.2
  carousel_slider: ^4.2.1
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  get_storage: ^2.0.3
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  google_places_autocomplete_text_field: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.3.0
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .env
    - assets/images/google.svg
    - assets/images/profile_placeholder.png

flutter_intl:
  enabled: true
  assets:
    - assets/images/intro-image.jpg
    - assets/images/hike-icon.svg
