name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  intl: ^0.18.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  provider: ^6.0.3
  cupertino_icons: ^1.0.6
  go_router: ^14.1.3
  image_picker: ^0.8.4+4
  http_parser: ^4.0.0
  google_sign_in: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  easy_localization: ^3.0.0
  flutter_translate: ^3.0.0
  xml: ^5.3.1
  file_picker: ^8.0.5
  weather: ^3.1.1
  lottie: ^3.1.2
  carousel_slider: ^4.0.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^1.0.3
  get: ^4.6.6
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_utils: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - assets/images/google.svg

flutter_intl:
  enabled: true

