version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: challenge
      POSTGRES_USER: admin
      POSTGRES_DB: challenge

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080