version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8888:8080

  postgres_test:
    image: postgres
    container_name: postgres_test
    ports:
      - 6501:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres_test:/var/lib/postgresql/data

volumes:
  postgres:
  postgres_test:
