version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: challenge2esgi2K24
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8888:8080
      
  postgres_test:
    image: postgres
    container_name: postgres_test
    ports:
      - 6501:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres_test:/var/lib/postgresql/data
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5005:5005
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  postgres:
  postgres_test:
