services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8888:8080

volumes:
  postgres: